- src: lutangar.steamcmd
- src: https://github.com/Gehock/ansible-nginx-revproxy
  name: hispanico.nginx_revproxy
- src: https://github.com/Gehock/ansible-role-podman
  name: chasinglogic.podman
- src: https://github.com/Gehock/ansible-role-opentofu
